package com.adultexample.mapper;

import com.adultexample.manager.dto.TreeNodeDto;
import com.adultexample.pojo.SResource;
import com.adultexample.pojo.SResourceExample;
import com.adultexample.pojo.SResourceKey;
import com.adultexample.pojo.TreeNode;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    long countByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int deleteByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int deleteByPrimaryKey(SResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int insert(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int insertSelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    List<SResource> selectByExample(SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    SResource selectByPrimaryKey(SResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByExample(@Param("record") SResource record, @Param("example") SResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByPrimaryKeySelective(SResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_resource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByPrimaryKey(SResource record);

	int selectBrother(Map map);

	int deleteSroleResource(Map map);

	int insertSroleResource(Map map);

	List<TreeNodeDto> selectAll();

	List<TreeNode> selectRes(Integer roleId);

	int selectSroleResource(Map map);

	void insertParentChild(Map map);

	void deleteParentChild(Map map);

	int selectOtherChild(Map map);

	int selectParent(Map map);

	List selectResList(Integer roleid);
}