package com.adultexample.mapper;

import com.adultexample.pojo.SRoleresource;
import com.adultexample.pojo.SRoleresourceExample;
import com.adultexample.pojo.SRoleresourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SRoleresourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    long countByExample(SRoleresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int deleteByExample(SRoleresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int deleteByPrimaryKey(SRoleresourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int insert(SRoleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int insertSelective(SRoleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    List<SRoleresource> selectByExample(SRoleresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    SRoleresource selectByPrimaryKey(SRoleresourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") SRoleresource record, @Param("example") SRoleresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByExample(@Param("record") SRoleresource record, @Param("example") SRoleresourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByPrimaryKeySelective(SRoleresource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_roleresource
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    int updateByPrimaryKey(SRoleresource record);
}