package com.adultexample.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.adultexample.pojo.SRole;
import com.adultexample.pojo.SRoleExample;

public interface SRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    long countByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int deleteByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int insert(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int insertSelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    List<SRole> selectByExample(SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    SRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByExample(@Param("record") SRole record, @Param("example") SRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByPrimaryKeySelective(SRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_role
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByPrimaryKey(SRole record);
    
    /* ................................................................. */
    
    int deleteByIds(Integer[] ids);
}