package com.adultexample.mapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.adultexample.dto.UserDto;
import com.adultexample.manager.dto.LeftData;
import com.adultexample.pojo.SUser;
import com.adultexample.pojo.SUserExample;

public interface SUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    long countByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int deleteByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int insert(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int insertSelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    List<SUser> selectByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    SUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByExample(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByPrimaryKeySelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user
     *
     * @mbg.generated Fri Dec 13 11:09:12 CST 2019
     */
    int updateByPrimaryKey(SUser record);
    
    /*.........................................................*/
    
    //用户名 --- 负责人
	List<SUser> selectUsername();
	List<SUser> selectAll();
	
	//左侧列表
	List<LeftData> selectRes(int roleid);
	
	//用户名密码
	SUser selectUser(SUser user);
	
	 //完整查询
    List<UserDto> selectByPage(SUser user);
    //批量删除
    int deleteByIds(Integer[] ids);

	
}