package com.adultexample.mapper;

import com.adultexample.door.dto.DChapterDto;
import com.adultexample.manager.dto.ChapterDto;
import com.adultexample.pojo.TChapter;
import com.adultexample.pojo.TChapterExample;
import com.adultexample.pojo.TChapterKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TChapterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    long countByExample(TChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByExample(TChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByPrimaryKey(TChapterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insert(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insertSelective(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    List<TChapter> selectByExample(TChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    TChapter selectByPrimaryKey(TChapterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TChapter record, @Param("example") TChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExample(@Param("record") TChapter record, @Param("example") TChapterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKeySelective(TChapter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_chapter
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKey(TChapter record);
    
    
    
    /*----------------------------------------------------*/
    
    /**
     * 获取章节分页内容
     * @param checkname
     * @return
     */
	List<ChapterDto> selectPageInfo(String checkname);
	/**
	 * 批量删除数据
	 * @param ids
	 * @return
	 */
	int deletesByIds(Integer[] ids);
	
	/**
	 * 前台查询，章节练习
	 * @param id
	 * @return
	 */
	List<DChapterDto> selectChapterLearn(Integer id);
}