package com.adultexample.mapper;

import com.adultexample.pojo.TCollection;
import com.adultexample.pojo.TCollectionExample;
import com.adultexample.pojo.TCollectionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    long countByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int deleteByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int deleteByPrimaryKey(TCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int insert(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int insertSelective(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    List<TCollection> selectByExample(TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    TCollection selectByPrimaryKey(TCollectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") TCollection record, @Param("example") TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int updateByExample(@Param("record") TCollection record, @Param("example") TCollectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int updateByPrimaryKeySelective(TCollection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_collection
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    int updateByPrimaryKey(TCollection record);
}