package com.adultexample.mapper;

import com.adultexample.manager.dto.PaperDto;
import com.adultexample.pojo.TPaper;
import com.adultexample.pojo.TPaperExample;
import com.adultexample.pojo.TPaperKey;
import com.adultexample.pojo.TPaperWithBLOBs;
import com.adultexample.pojo.TQuestionWithBLOBs;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    long countByExample(TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByExample(TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByPrimaryKey(TPaperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insert(TPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insertSelective(TPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    List<TPaperWithBLOBs> selectByExampleWithBLOBs(TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    List<TPaper> selectByExample(TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    TPaperWithBLOBs selectByPrimaryKey(TPaperKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TPaperWithBLOBs record, @Param("example") TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TPaperWithBLOBs record, @Param("example") TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExample(@Param("record") TPaper record, @Param("example") TPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKeySelective(TPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_paper
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKey(TPaper record);

    /*-----------------------------------------------------*/
    
    /**
     * 查询分页信息
     * @param checkname
     * @return
     */
	List<PaperDto> selectPageInfo(String checkname);
	/**
	 * 批量删除
	 * @param ids
	 */
	int deleteByIds(Integer[] ids);
	/**
	 * 根据id查询 完整信息
	 * @param id
	 * @return
	 */
	TPaperWithBLOBs selectById(Integer id);

	/**
	 * 前台查询指定条件试卷信息
	 * @param map
	 * @return
	 */
	List<TPaperWithBLOBs> selectExamplePaper(Map map);

	/**
	 * 保存试卷信息
	 * @param paper
	 * @return
	 */
	int insertPaper(TPaperWithBLOBs paper);
	
}