package com.adultexample.mapper;

import com.adultexample.manager.dto.SubjectDto;
import com.adultexample.pojo.TSubject;
import com.adultexample.pojo.TSubjectExample;
import com.adultexample.pojo.TSubjectKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    long countByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int deleteByPrimaryKey(TSubjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insert(TSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int insertSelective(TSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    List<TSubject> selectByExample(TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    TSubject selectByPrimaryKey(TSubjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TSubject record, @Param("example") TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByExample(@Param("record") TSubject record, @Param("example") TSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKeySelective(TSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_subject
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    int updateByPrimaryKey(TSubject record);
    
    
    
/*-----------------------------------------------------------*/
   
    
    /**
     * 查询分页内容
     * @param checkname
     * @return
     */
	List<SubjectDto> selectPage(String checkname);
	
	/**
	 * 查询父类型(id,name)
	 * @return
	 */
	List<TSubject> selectParNameList();
	
	/**
	 * 批量删除
	 * @param ids
	 * @return
	 */
	int deleteByIds(Integer[] ids);

	/**
	 * 前台首页左侧列表
	 * @return
	 */
	List<com.adultexample.door.dto.SubjectDto> selectLeftList();
}