package com.adultexample.pojo;

public class SCustKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.ID
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.ID
     *
     * @return the value of s_cust.ID
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.ID
     *
     * @param id the value for s_cust.ID
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }
}