package com.adultexample.pojo;

public class SCust extends SCustKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.pwd
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.status
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.url
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.realName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.sex
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.birthday
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.mobile
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.regDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String regdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.lastLoginDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String lastlogindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.emain
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String emain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.nickName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.idcard
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.pwd
     *
     * @return the value of s_cust.pwd
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.pwd
     *
     * @param pwd the value for s_cust.pwd
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.status
     *
     * @return the value of s_cust.status
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.status
     *
     * @param status the value for s_cust.status
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.url
     *
     * @return the value of s_cust.url
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.url
     *
     * @param url the value for s_cust.url
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.realName
     *
     * @return the value of s_cust.realName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.realName
     *
     * @param realname the value for s_cust.realName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.sex
     *
     * @return the value of s_cust.sex
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.sex
     *
     * @param sex the value for s_cust.sex
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.birthday
     *
     * @return the value of s_cust.birthday
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.birthday
     *
     * @param birthday the value for s_cust.birthday
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.mobile
     *
     * @return the value of s_cust.mobile
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.mobile
     *
     * @param mobile the value for s_cust.mobile
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.regDate
     *
     * @return the value of s_cust.regDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getRegdate() {
        return regdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.regDate
     *
     * @param regdate the value for s_cust.regDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setRegdate(String regdate) {
        this.regdate = regdate == null ? null : regdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.lastLoginDate
     *
     * @return the value of s_cust.lastLoginDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getLastlogindate() {
        return lastlogindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.lastLoginDate
     *
     * @param lastlogindate the value for s_cust.lastLoginDate
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setLastlogindate(String lastlogindate) {
        this.lastlogindate = lastlogindate == null ? null : lastlogindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.emain
     *
     * @return the value of s_cust.emain
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getEmain() {
        return emain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.emain
     *
     * @param emain the value for s_cust.emain
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setEmain(String emain) {
        this.emain = emain == null ? null : emain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.nickName
     *
     * @return the value of s_cust.nickName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.nickName
     *
     * @param nickname the value for s_cust.nickName
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.idcard
     *
     * @return the value of s_cust.idcard
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.idcard
     *
     * @param idcard the value for s_cust.idcard
     *
     * @mbg.generated Tue Mar 03 22:38:56 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }
}