package com.adultexample.pojo;

public class SRoleresource extends SRoleresourceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_roleresource.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_roleresource.resourceId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer resourceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_roleresource.roleId
     *
     * @return the value of s_roleresource.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_roleresource.roleId
     *
     * @param roleid the value for s_roleresource.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_roleresource.resourceId
     *
     * @return the value of s_roleresource.resourceId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_roleresource.resourceId
     *
     * @param resourceid the value for s_roleresource.resourceId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }
}