package com.adultexample.pojo;

public class SRole extends SRoleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.roleName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_role.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.roleName
     *
     * @return the value of s_role.roleName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.roleName
     *
     * @param rolename the value for s_role.roleName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_role.status
     *
     * @return the value of s_role.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_role.status
     *
     * @param status the value for s_role.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}