package com.adultexample.pojo;

public class SRoleresourceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_roleresource.id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_roleresource.id
     *
     * @return the value of s_roleresource.id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_roleresource.id
     *
     * @param id the value for s_roleresource.id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }
}