package com.adultexample.pojo;

public class SUser extends SUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.s_o_id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer sOId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.realName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.sex
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.phone
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.loginAccount
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String loginaccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.pwd
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.lastLogin
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private String lastlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    private Integer roleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.s_o_id
     *
     * @return the value of s_user.s_o_id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getsOId() {
        return sOId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.s_o_id
     *
     * @param sOId the value for s_user.s_o_id
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setsOId(Integer sOId) {
        this.sOId = sOId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.realName
     *
     * @return the value of s_user.realName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.realName
     *
     * @param realname the value for s_user.realName
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.sex
     *
     * @return the value of s_user.sex
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.sex
     *
     * @param sex the value for s_user.sex
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.phone
     *
     * @return the value of s_user.phone
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.phone
     *
     * @param phone the value for s_user.phone
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.loginAccount
     *
     * @return the value of s_user.loginAccount
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getLoginaccount() {
        return loginaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.loginAccount
     *
     * @param loginaccount the value for s_user.loginAccount
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setLoginaccount(String loginaccount) {
        this.loginaccount = loginaccount == null ? null : loginaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.pwd
     *
     * @return the value of s_user.pwd
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.pwd
     *
     * @param pwd the value for s_user.pwd
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.status
     *
     * @return the value of s_user.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.status
     *
     * @param status the value for s_user.status
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.lastLogin
     *
     * @return the value of s_user.lastLogin
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public String getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.lastLogin
     *
     * @param lastlogin the value for s_user.lastLogin
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setLastlogin(String lastlogin) {
        this.lastlogin = lastlogin == null ? null : lastlogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.roleId
     *
     * @return the value of s_user.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.roleId
     *
     * @param roleid the value for s_user.roleId
     *
     * @mbg.generated Fri Feb 21 18:09:01 CST 2020
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
}