package com.adultexample.pojo;

public class TCollectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.ID
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.ID
     *
     * @return the value of t_collection.ID
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.ID
     *
     * @param id the value for t_collection.ID
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }
}