package com.adultexample.pojo;

public class TCollection extends TCollectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.cusId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    private Integer cusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.questionId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    private Integer questionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_collection.createDate
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    private String createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.cusId
     *
     * @return the value of t_collection.cusId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public Integer getCusid() {
        return cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.cusId
     *
     * @param cusid the value for t_collection.cusId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public void setCusid(Integer cusid) {
        this.cusid = cusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.questionId
     *
     * @return the value of t_collection.questionId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.questionId
     *
     * @param questionid the value for t_collection.questionId
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_collection.createDate
     *
     * @return the value of t_collection.createDate
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_collection.createDate
     *
     * @param createdate the value for t_collection.createDate
     *
     * @mbg.generated Sun Mar 08 08:30:37 CST 2020
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }
}