package com.adultexample.pojo;

public class TPaper extends TPaperKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.creater_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String createrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.down_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private Integer downHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.open_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private Integer openHits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_paper.point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String point;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.subject_id
     *
     * @return the value of t_paper.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.subject_id
     *
     * @param subjectId the value for t_paper.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.creater_id
     *
     * @return the value of t_paper.creater_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getCreaterId() {
        return createrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.creater_id
     *
     * @param createrId the value for t_paper.creater_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setCreaterId(String createrId) {
        this.createrId = createrId == null ? null : createrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.name
     *
     * @return the value of t_paper.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.name
     *
     * @param name the value for t_paper.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.type
     *
     * @return the value of t_paper.type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.type
     *
     * @param type the value for t_paper.type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.year
     *
     * @return the value of t_paper.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.year
     *
     * @param year the value for t_paper.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.down_hits
     *
     * @return the value of t_paper.down_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public Integer getDownHits() {
        return downHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.down_hits
     *
     * @param downHits the value for t_paper.down_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setDownHits(Integer downHits) {
        this.downHits = downHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.open_hits
     *
     * @return the value of t_paper.open_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public Integer getOpenHits() {
        return openHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.open_hits
     *
     * @param openHits the value for t_paper.open_hits
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setOpenHits(Integer openHits) {
        this.openHits = openHits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_paper.point
     *
     * @return the value of t_paper.point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_paper.point
     *
     * @param point the value for t_paper.point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }
}