package com.adultexample.pojo;

public class TQuestion extends TQuestionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.question_type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.chapter_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.review_point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String reviewPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.score
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.audit_status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String auditStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.question_type
     *
     * @return the value of t_question.question_type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.question_type
     *
     * @param questionType the value for t_question.question_type
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.subject_id
     *
     * @return the value of t_question.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.subject_id
     *
     * @param subjectId the value for t_question.subject_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId == null ? null : subjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.chapter_id
     *
     * @return the value of t_question.chapter_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.chapter_id
     *
     * @param chapterId the value for t_question.chapter_id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId == null ? null : chapterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.review_point
     *
     * @return the value of t_question.review_point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getReviewPoint() {
        return reviewPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.review_point
     *
     * @param reviewPoint the value for t_question.review_point
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setReviewPoint(String reviewPoint) {
        this.reviewPoint = reviewPoint == null ? null : reviewPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.year
     *
     * @return the value of t_question.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.year
     *
     * @param year the value for t_question.year
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.score
     *
     * @return the value of t_question.score
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.score
     *
     * @param score the value for t_question.score
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.audit_status
     *
     * @return the value of t_question.audit_status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.audit_status
     *
     * @param auditStatus the value for t_question.audit_status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }
}