package com.adultexample.pojo;

public class TQuestionWithBLOBs extends TQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.content
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.answer
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_question.analysis
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String analysis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.content
     *
     * @return the value of t_question.content
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.content
     *
     * @param content the value for t_question.content
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.answer
     *
     * @return the value of t_question.answer
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.answer
     *
     * @param answer the value for t_question.answer
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_question.analysis
     *
     * @return the value of t_question.analysis
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_question.analysis
     *
     * @param analysis the value for t_question.analysis
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }
}