package com.adultexample.pojo;


public class TSubject extends TSubjectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.sort
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.create_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.create_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.update_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.update_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.remarks
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.parentno
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private Integer parentno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.name
     *
     * @return the value of t_subject.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.name
     *
     * @param name the value for t_subject.name
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.sort
     *
     * @return the value of t_subject.sort
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.sort
     *
     * @param sort the value for t_subject.sort
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.create_by
     *
     * @return the value of t_subject.create_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.create_by
     *
     * @param createBy the value for t_subject.create_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.create_date
     *
     * @return the value of t_subject.create_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.create_date
     *
     * @param createDate the value for t_subject.create_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.update_by
     *
     * @return the value of t_subject.update_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.update_by
     *
     * @param updateBy the value for t_subject.update_by
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.update_date
     *
     * @return the value of t_subject.update_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.update_date
     *
     * @param updateDate the value for t_subject.update_date
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.remarks
     *
     * @return the value of t_subject.remarks
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.remarks
     *
     * @param remarks the value for t_subject.remarks
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.status
     *
     * @return the value of t_subject.status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.status
     *
     * @param status the value for t_subject.status
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.parentno
     *
     * @return the value of t_subject.parentno
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public Integer getParentno() {
        return parentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.parentno
     *
     * @param parentno the value for t_subject.parentno
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setParentno(Integer parentno) {
        this.parentno = parentno;
    }
}