package com.adultexample.pojo;

public class TSubjectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_subject.id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_subject.id
     *
     * @return the value of t_subject.id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_subject.id
     *
     * @param id the value for t_subject.id
     *
     * @mbg.generated Wed Feb 26 20:15:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }
}